### ISSUE TITLE
incorporate ox-hugo's tree-matching logic

### ISSUE THREAD

**Issue by titaniumbones** [titaniumbones/ox-huveal#4]
popping up to the top-level subtree to export a lecture is a pain.  a better solution is to repurpose [the ox-hugo export subtree validation method](https://github.com/kaushalmodi/ox-hugo/blob/7c9d6994296087eee40a5aedae0708961f47808c/ox-hugo.el#L1500-L1562) that @kaushalmodi has developed.  This is a reminder to read through that code and steal it, since ox-hugo is in any case a dependency.

**Comment by titaniumbones** [comment]
looks like `:filter-final-output` is the place to define this. One options would be to continue using `org-reveal-root`, `org-reveal-extra-css`, org-reveal-extra-js`, etc. -- so, remove the `huveal` template functions --, and then just replace the `org-revewal` paths with the `org-huveal` equivalents at the end.  THat should cut hte size of `ox-huveal.el` by more than half and reduce bitrot.

**Comment by titaniumbones** [comment]
hmm. i don't quite understand what's going on in Kaushal's code. It's not clear to me how the exporter learns that the subtree has been moved up to the valid subtree.

**Comment by kaushalmodi** [comment]
You need just the [`org-hugo--get-valid-subtree`][1]; the link in your post above includes `org-hugo--get-post-subtree-coordinates` too. That latter function is needed only for subtree weight calculation.

The job of `org-hugo--get-valid-subtree` is simple.. it keeps on doing `org-up-heading-safe` until it reaches a heading that has the `EXPORT_FILE_NAME` property defined. If it reaches level 1 (the top-most level) while doing so, and still doesn't find that property, it returns nil.

[1]: https://github.com/kaushalmodi/ox-hugo/blob/7c9d6994296087eee40a5aedae0708961f47808c/ox-hugo.el#L1500-L1519
